@startuml

namespace ProjectAssets {
    class Game <<Component>> {
        LocationState locationState
        CharacterState characterState
        LocationRepository locationRepository
        CharacterRepository characterRepository
        Location location
        Interaction interaction
    }
    Game "1" o-- "1" Locations.Location
    Game "1" o-- "1" Characters.Interaction
}

namespace ProjectAssets.Data  {
    class LocationSpotCharacter {
        string characterName
        LocationSpotMapping spot
    }

    class PlayerData {
        +Rule InteractRule
    }
}

namespace ProjectAssets.Repositories {
    class LocationRepository <<Repository>> {
        +LocationView GetLocationView(LocationName)
    }

    class CharacterRepository <<Repository>> {
        CharacterData GetCharacterData(CharacterName)
    }

    class LocationSpotCharacterRepository <<Repository>> {
        LocationSpotCharacter LoadLocationSpot()
    }
}

namespace ProjectAssets.Characters {
    class Interaction <<Component>> {
        InteractionView view
    }

    class InteractionView <<View>> {
        +Update(CharacterData)
    }

    class CharacterState <<LogicBlock>> {
        Characters.State currentState
        void Input(Input input)
        void When<State>()
    }

    Interaction "1" *-- "1" InteractionView 
}

namespace ProjectAssets.Characters.Rules <<Rectangle>> {
    class Reaction {

    }

    class Rule {
    }

    class InteractRule {
        InteractRuleName ruleName
    }

    interface IRuleSet<Rule> {
        IList<Rule> AllRules()
        IList<Rule> Filter(Func<bool>)
    }

    class RuleSet<Rule> implements IRuleSet{
        -IList<Rule> rules
        +IList<Rule> AllRules()
        +IList<Rule> Filter(Func<bool>)
    }

    Rule *-- InteractRule
}

namespace ProjectAssets.Characters.Data <<Rectangle>> {
    class CharacterData <<Resource>> {
        +string FirstName
        +string LastName
        +CharacterInteractImages InteractImages
    }

    class CharacterInteractImages <<Resource>> {
        +Texture2D Default
        +Texture2D Startled
        +Texture2D Surprised
    }

}

namespace ProjectAssets.Characters.Input <<Rectangle>> {
    struct Stop {

    }

    struct Interact {
        CharacterData character
    }

    struct Ask {
        CharacterData character
    }

    struct Talk {
        CharacterData character
    }
}

namespace ProjectAssets.Characters.State <<Rectangle>> {
    class Stop {
        void Input(Input.Interact input)
    }

    class Interact {
        void Input(Input.Stop input)
        void Input(Input.Ask input)
        void Input(Input.Talk input)
    }

    class Ask {
        void Input(Input.Stop input)
        void Input(Input.Interact input)
    }

    class Talk {
        void Input(Input.Stop input)
        void Input(Input.Interact input)
    }
}

namespace ProjectAssets.Locations {
    class Location <<Component>> {
        LocationView view
        LocationRepository locationRepository
    }

    class LocationView <<View>> {
        +Texture2D BG
        +RedirectButton[] Buttons
        +LocationName LocationName
    }

    class RedirectButton <<Component>> { 
        + LocationName TargetLocation
        + string Text
        LocationState locationState
        onClick()
    }

    class LocationSpot <<Component>> {
        LocationSpotView view
    
    }

    class LocationSpotView <<View>> {
        +Texture2D OccupiedImage
        +Area2d MouseArea 
        +LocationSpotName locationSpotName
        CharacteerState characterState
    }

    class LocationState <<LogicBlock>> {
        Locations.State currentState
        void Input(Input input)
        void When<State>()
    }

    RedirectButton ..> LocationState
    RedirectButton "1" --* "1" Data.LocationName  

    Location "1" o-- "1" LocationView : Sets

    LocationSpot "1" *-- "1" LocationSpotView

    LocationSpotView ..> CharacterState
    LocationSpotView "1" *-- "1" Data.LocationSpotName

    LocationView "1" *-- "0..*" LocationSpot
    LocationView "1" o-- "1..*" RedirectButton
    LocationView "1" *-- "1" Data.LocationName
}


namespace ProjectAssets.Locations.Data <<Rectangle>> {
    class LocationName {
        string LocationName
    } 

    class LocationSpotName {
        string LocationName
    }

    class LocationSpotMapping {
        LocationName LocationName
        LocationSpotName LocationSpotName
    }

    LocationSpotMapping "1" --* LocationSpotName
    LocationSpotMapping "1" --* LocationName
}

namespace ProjectAssets.Locations.Input <<Rectangle>> {
    struct Stop { }

    struct Show { }

    struct ChangeLocation {
        string LocationName
    }
}

namespace ProjectAssets.Locations.State <<Rectangle>> {
    class Active {
        LocationRepository locationRepository

        void Input(Input.ChangeLocation input)
        void Input(Input.Stop input)
    }

    class Stop {
        void Input(Input.Show input)
    } 
    Active ..> LocationRepository
}

@enduml