@startuml


package ProjectAssets
{
    class Game {
        LocationState locationState
        CharacterState characterState
        LocationRepository locationRepository
    }

    package Repositories {
        class LocationRepository {
            LocationView GetLocationView(string Name)
        }
    }

    package Locations {
        LogicBlock ()-- LocationState 
        package LocationState <<Rectangle>>
        {
            class LocationState {
                void Input(Input input)
                void When<State>()
            }

            package Input <<Rectangle>>{
                class Input.Stop { }

                class Input.Show { }

                class Input.ChangeLocation {
                    string LocationName
                }
            }

            package State <<Rectangle>>{
                class State.Active {
                    LocationRepository locationRepository

                    void Input(Input.ChangeLocation input)
                    void Input(Input.Stop input)
                }

                class State.Stop {
                    void Input(Input.Active input)
                } 
                State.Active ..> LocationRepository

            }
        }

        class Location {
            LocationView view
        }

        class LocationView {
            RedirectButton[] buttons
        }

        class RedirectButton { 
            string locationName
            LocationState locationState
            onClick()
        }

        class LocationSpot {
            LocationSpotView view
        }

        class LocationSpotView {
            LocationSpot[] locationSpot
        }

        LocationView ..> LocationState
        LocationSpotView ..> LocationState
        RedirectButton ..> LocationState

        LocationView "1" o-- "1..*" RedirectButton
    }
}


@enduml